ingredient_cuisine_mapping = {
"acorn": ["American", "White Mountain Apache Tribe cuisine"],
"alpinia galanga": ["Southeast Asian"],
"amaranth": ["Incan"],
"arrowroot": ["Vegan"],
"atta flour": ["Indian"],
"bagoong Monamon": ["Filipino"],
"bagoong Terong": ["Filipino"],
"banh canh": ["Vietnamese"],
"black bean paste": ["Chinese", "Taiwanese"],
"black pepper": ["Indonesian", "Sausage"],
"budu": ["Malaysian", "Thai"],
"candlenut": ["Indonesian"],
"cardamom": ["Indonesian"],
"caviar": ["Haute cuisine"],
"challah": ["Jewish cuisine"],
"charcuterie": ["Sausage"],
"chard": ["Mediterranean"],
"chayote": ["Taiwanese", "Mexican"],
"chia": ["Aztec"],
"chicken": ["Sausage"],
"chili pepper": ["Singaporean cuisine", "Indian", "Incan", "Malaysian", "Mexican", "Thai", "Indonesian", "Vietnamese"],
"cinnamon": ["Indonesian"],
"clove": ["Indonesian"],
"coconut": ["Singaporean cuisine"],
"coconut milk": ["Thai", "Indonesian", "Malaysian", "Filipino"],
"coriander": ["Chinese", "Indian"],
"crab": ["Singaporean cuisine"],
"crab meat": ["Cajun", "Louisiana Creole cuisine", "American", "Malaysian", "Chinese", "Japanese Cuisine"],
"crawfish tail": ["Cajun", "Louisiana Creole cuisine"],
"cubeb": ["Indonesian"],
"cumin": ["Indonesian"],
"escolar": ["European", "Asian"],
"fennel": ["Indonesian"],
"fish sauce": ["Vietnamese", "Filipino"],
"flour": ["Pizza"],
"foie gras": ["Haute cuisine"],
"frijoles Negros": ["Mexican", "Vegan", "Vegetarian"],
"galangal": ["Southeast Asian", "Indonesian"],
"ground beef": ["Sausage"],
"guanciale": ["Italian"],
"ham": ["American", "Portuguese", "German", "Spanish Cuisine", "Italian", "Filipino", "French", "Chinese", "Romanian"],
"hollandaise sauce": ["French"],
"ipomoea aquatica": ["Singaporean cuisine", "Indonesian"],
"jell-O": ["American"],
"lamb": ["Welsh cuisine", "Middle Eastern"],
"lard": ["Sausage"],
"lemongrass": ["Indonesian"],
"maida flour": ["Indian"],
"marsala wine": ["Italian"],
"meat analogue": ["Chinese", "Vegan cuisine", "Vegetarian"],
"mirin": ["Japanese Cuisine"],
"monosodium glutamate": ["Chinese"],
"mud": ["Chinese"],
"nutmeg": ["Indonesian"],
"olive oil": ["Pizza"],
"osake Kazu": ["Japanese Cuisine"],
"oyster": ["Chinese"],
"oyster sauce": ["Chinese"],
"parmigiano Reggiano": ["Italian"],
"parsley": ["Sausage"],
"pasta": ["Italian"],
"peanut": ["Indonesian"],
"pecan": ["American"],
"pecorino Romano": ["Italian"],
"pinole": ["Mexican"],
"pork": ["Sausage"],
"prawn cracker": ["Indonesian"],
"prosciutto": ["Italian"],
"puff pastry": ["Haute cuisine"],
"quail": ["Haute cuisine"],
"quinoa": ["Incan", "Vegan", "Vegetarian"],
"roux": ["Louisiana Creole cuisine", "Cajun", "French"],
"salvia": ["Mediterranean", "Italian"],
"salvia hispanica": ["Aztec"],
"sausage": ["German", "Italian", "Polish", "Cajun"],
"schmaltz": ["Jewish cuisine"],
"shahe fen": ["Singaporean cuisine"],
"shrimp": ["Singaporean cuisine"],
"shrimp paste": ["Singaporean cuisine", "Indonesian"],
"soy sauce": ["Indonesian"],
"star anise": ["Indonesian"],
"table salt": ["Sausage", "Pizza"],
"tamarind": ["Indonesian"],
"tempeh": ["Indonesian"],
"tofu": ["Indonesian"],
"tomato": ["Chilean", "American", "Italian"],
"truffle": ["Haute cuisine"],
"turmeric": ["Indonesian", "Indian"],
"water": ["Pizza"],
"yeast": ["Pizza"],
}
