ingredient_cuisine_mapping = {
"Acorn": ["American", "White Mountain Apache Tribe cuisine"],
"Alpinia galanga": ["Southeast Asian"],
"Amaranth": ["Incan"],
"Arrowroot": ["Vegan"],
"Atta flour": ["Indian"],
"Bagoong Monamon": ["Filipino"],
"Bagoong Terong": ["Filipino"],
"Banh canh": ["Vietnamese"],
"Black bean paste": ["Chinese", "Taiwanese"],
"Black pepper": ["Indonesian", "Sausage"],
"Budu": ["Malaysian", "Thai"],
"Candlenut": ["Indonesian"],
"Cardamom": ["Indonesian"],
"Caviar": ["Haute cuisine"],
"Challah": ["Jewish cuisine"],
"Charcuterie": ["Sausage"],
"Chard": ["Mediterranean"],
"Chayote": ["Taiwanese", "Mexican"],
"Chia": ["Aztec"],
"Chicken": ["Sausage"],
"Chili pepper": ["Singaporean cuisine", "Indian", "Incan", "Malaysian", "Mexican", "Thai", "Indonesian", "Vietnamese"],
"Cinnamon": ["Indonesian"],
"Clove": ["Indonesian"],
"Coconut": ["Singaporean cuisine"],
"Coconut milk": ["Thai", "Indonesian", "Malaysian", "Filipino"],
"Coriander": ["Chinese", "Indian"],
"Crab": ["Singaporean cuisine"],
"Crab meat": ["Cajun", "Louisiana Creole cuisine", "American", "Malaysian", "Chinese", "Japanese Cuisine"],
"Crawfish tails": ["Cajun", "Louisiana Creole cuisine"],
"Cubeb": ["Indonesian"],
"Cumin": ["Indonesian"],
"Escolar": ["European", "Asian"],
"Fennel": ["Indonesian"],
"Fish sauce": ["Vietnamese", "Filipino"],
"Flour": ["Pizza"],
"Foie gras": ["Haute cuisine"],
"Frijoles Negros": ["Mexican", "Vegan", "Vegetarian"],
"Galangal": ["Southeast Asian", "Indonesian"],
"Ground beef": ["Sausage"],
"Guanciale": ["Italian"],
"Ham": ["American", "Portuguese", "German", "Spanish Cuisine", "Italian", "Filipino", "French", "Chinese", "Romanian"],
"Hollandaise sauce": ["French"],
"Ipomoea aquatica": ["Singaporean cuisine", "Indonesian"],
"Jell-O": ["American"],
"Lamb": ["Welsh cuisine", "Middle Eastern"],
"Lard": ["Sausage"],
"Lemongrass": ["Indonesian"],
"Maida flour": ["Indian"],
"Marsala wine": ["Italian"],
"Meat analogue": ["Chinese", "Vegan cuisine", "Vegetarian"],
"Mirin": ["Japanese Cuisine"],
"Monosodium glutamate": ["Chinese"],
"Mud": ["Chinese"],
"Nutmeg": ["Indonesian"],
"Olive oil": ["Pizza"],
"Osake Kazu": ["Japanese Cuisine"],
"Oyster": ["Chinese"],
"Oyster sauce": ["Chinese"],
"Parmigiano Reggiano": ["Italian"],
"Parsley": ["Sausage"],
"Pasta": ["Italian"],
"Peanut": ["Indonesian"],
"Pecan": ["American"],
"Pecorino Romano": ["Italian"],
"Pinole": ["Mexican"],
"Pork": ["Sausage"],
"Prawn cracker": ["Indonesian"],
"Prosciutto": ["Italian"],
"Puff pastry": ["Haute cuisine"],
"Quail": ["Haute cuisine"],
"Quinoa": ["Incan", "Vegan", "Vegetarian"],
"Roux": ["Louisiana Creole cuisine", "Cajun", "French"],
"Salvia": ["Mediterranean", "Italian"],
"Salvia hispanica": ["Aztec"],
"Sausage": ["German", "Italian", "Polish", "Cajun"],
"Schmaltz": ["Jewish cuisine"],
"Shahe fen": ["Singaporean cuisine"],
"Shrimp": ["Singaporean cuisine"],
"Shrimp paste": ["Singaporean cuisine", "Indonesian"],
"Soy sauce": ["Indonesian"],
"Star anise": ["Indonesian"],
"Table salt": ["Sausage", "Pizza"],
"Tamarind": ["Indonesian"],
"Tempeh": ["Indonesian"],
"Tofu": ["Indonesian"],
"Tomato": ["Chilean", "American", "Italian"],
"Truffle": ["Haute cuisine"],
"Turmeric": ["Indonesian", "Indian"],
"Water": ["Pizza"],
"Yeast": ["Pizza"],
}
